### ISSUE TITLE
Using the old argument syntax produces a segmentation fault.

### ISSUE THREAD

**Issue by jprendes** [benhj/arrow#13]
Running the factorial script using the old argument syntax causes a segmentation fault.

run: `./arrow factorial.ar 5`
where `factorial.ar` is:
```
fn factorial(n) -> f {
    1 -> f;
    if (n > 1) {     
        n * factorial(n - 1) -> f;
    }
}

start {
    arg 0 -> N; ;;; note the use of `arg 0` instead of `arg(0)`
    pr "result: "; prn factorial(N);
}
```

Expected result: Parse error
Actual result: Segmentation fault

**Comment by jprendes** [comment]
In this case, `arg 0 -> N` is evaluated as an `ArrowStatement`.
The `ArrowStatement` is added to the `ScopedBlockStatement`.
When `ScopedBlockStatement` is evaluated, it calls `statement->getEvaluator()->evaluate(environment)`.
Since `statement` is an `ArrowStatement`, the call to `getEvaluator()` returns `nullptr`, resulting in a segmentation fault.

I wonder this situation can happen with any other type of statements too.

**Comment by benhj** [comment]
Thanks Jorge. Will probably be getting rid of `ArrowStatement` as it’s only being used by `stoi` currently and that should really be a built in expression anyway — one that can be used within a `SimpleArrowStatement` (and then maybe `SimpleArrowStatement` should just be renamed `ArrowStatement`) 🧐

**Comment by benhj** [comment]
This is now fixed. I have removed all `ArrowStatement` usage and deleted the type. This was obsolete code and the only function that relied on it was a statement for converting a string to an integer. This will be re-introduced as an expression at some point later.
