### ISSUE TITLE
Running argtest.ar fails with "Parse error" if the argument is not numeric

### ISSUE THREAD

**Issue by jprendes** [benhj/arrow#17]
Running `./arrow ../examples/argtest.ar hello` prints `Error: Parse error`
Running `./arrow ../examples/argtest.ar 123` prints `123`

I would expect `./arrow ../examples/argtest.ar hello` to print `hello`

**Comment by jprendes** [comment]
Ohhh, I see, I need to run `./arrow ../examples/argtest.ar '"hello"'`.
That seems a bit convoluted.

**Comment by benhj** [comment]
Fixed with a program arg tokenizer that no longer requires a string to be in double quotes.
