### ISSUE TITLE
Running `macroLike.ar` produces a parse error

### ISSUE THREAD

**Issue by jprendes** [benhj/arrow#19]
Running `./arrow ../examples/macroLike.ar` prints `Error: Unable to parse statement on line number 2`.
Expected result: running `./arrow ../examples/macroLike.ar` should print `3`

**Comment by benhj** [comment]
Thanks, yeah.. I originally added this when I experimented with permitting functions and other statements (e.g. if, while etc.) to have non scoped block expressions (`{…}`) but it broke some examples so I reverted it. Might remove this example as I’m not immediately planning on supporting this type of thing anymore.. could be nice though..

**Comment by benhj** [comment]
Completely removed this example
